Repository Arcucy/ArcLight, pull requests merged in 2020-09, with the labels that each got.

#130 🚑 Fixed file resolution issue
  src/pages/Podcast/Index.vue
  src/pages/Songs/Albums.vue
  src/pages/Songs/Index.vue
  src/pages/Songs/Singles.vue
  src/pages/Sound/Index.vue
  src/pages/User/_id.vue
Labels: bug-fixed, critical

#131 🚑 Fixed user balance 0 or transaction error handling
  src/api/arweave.js
  src/components/Header.vue
  src/store/index.js
Labels: bug-fixed, critical

#133 🚑 Fixed CSS issue
  src/pages/Upload/Album.vue
  src/pages/Upload/Podcast.vue
  src/pages/Upload/Single.vue
  src/pages/Upload/SoundEffect.vue
Labels: bug-fixed, critical

#145 🐛 Fixed introduction display issue and search issue
  src/components/Search.vue
  src/components/User/UserInfo.vue
Labels: bug-fixed

#149 🐛 Fix issue #148
  src/api/arweave.js
  src/components/User/UserInfo.vue
  src/pages/User/Edit.vue
Labels: bug-fixed

#159 ✨ Added a notice to user after upload
  src/pages/Upload/ReviewAlbum.vue
  src/pages/Upload/ReviewPodcast.vue
  src/pages/Upload/ReviewSingle.vue
  src/pages/Upload/ReviewSoundEffect.vue
Labels: enhancement

#160 ✨ Added text limits
  src/pages/Upload/Album.vue
  src/pages/Upload/Podcast.vue
  src/pages/Upload/Single.vue
  src/pages/Upload/SoundEffect.vue
Labels: bug-fixed, enhancement

#161 🚑 Fix critical value missing error
  src/pages/Upload/ReviewAlbum.vue
  src/pages/Upload/ReviewPodcast.vue
  src/pages/Upload/ReviewSingle.vue
  src/pages/Upload/ReviewSoundEffect.vue
Labels: bug-fixed, critical

#163 ✨ Now album can be download as a zip file, fixed price validation for Album uploads
  src/pages/Album/_id.vue
  src/pages/Upload/Album.vue
Labels: bug-fixed, critical, enhancement

#166 🐛 Fixed downloading pct issue and extention issue
  src/pages/Album/_id.vue
  src/pages/Music/_id.vue
  src/store/index.js
Labels: bug-fixed, critical

#169 ✨ Rewrite duration system and now dynamic calculation
  src/components/Layout/Space.vue
  src/components/Search.vue
  src/pages/Album/_id.vue
  src/pages/Upload/Album.vue
  src/pages/Upload/Podcast.vue
  src/pages/Upload/ReviewAlbum.vue
  src/pages/Upload/ReviewPodcast.vue
  src/pages/Upload/ReviewSingle.vue
  src/pages/Upload/ReviewSoundEffect.vue
  src/pages/Upload/Single.vue
  src/pages/Upload/SoundEffect.vue
Labels: bug-fixed, critical, enhancement

#179 ⚡ Optimize album processing speed
  README.md
  src/api/arweave.js
  src/pages/Upload/Album.vue
  src/pages/Upload/Podcast.vue
  src/pages/Upload/ReviewAlbum.vue
  src/pages/Upload/ReviewPodcast.vue
  src/pages/Upload/ReviewSingle.vue
  src/pages/Upload/ReviewSoundEffect.vue
  src/pages/Upload/Single.vue
  src/pages/Upload/SoundEffect.vue
  src/store/index.js
Labels: bug-fixed, enhancement

#181 ✨ Implemented the similar user recommendation function
  src/api/arweave.js
  src/components/User/UserCard.vue
  src/pages/Music/_id.vue
  src/pages/User/index.vue
Labels: bug-fixed, enhancement
