Repository Arcucy/ArcLight, pull requests merged in 2021-01, with the labels that each got.

#261 使 ArcLight 的价格可以显示为当前真实价值
  package.json
  src/App.vue
  src/api/api.js
  src/components/Header.vue
  src/components/Song/AlbumCard.vue
  src/components/Song/SingleCard.vue
  src/locales/en.js
  src/locales/ja-jp.js
  src/locales/zh-cn.js
  src/locales/zh-tw.js
  src/pages/Album/_id.vue
  src/pages/Music/_id.vue
  src/pages/Songs/Index.vue
  src/router/index.js
  src/store/index.js
  yarn.lock
Labels: enhancement

#279 ⚗ 代码清理以及动态加载音乐类型
  public/index.html
  src/api/arweave.js
  src/components/GenreSelect.vue
  src/components/Song/GenreFilter.vue
  src/components/imgUpload/imgUpload.vue
Labels: breaking-change, enhancement

#278 歌曲信息数据的本地缓存 & 登录框不会消失
  package.json
  src/api/arweave.js
  src/assets/image/cover_placeholder.png
  src/components/Header.vue
  src/components/Song/GetAudioInfo.vue
  src/components/Song/SingleCard.vue
  src/pages/Album/_id.vue
  src/pages/Music/_id.vue
  src/pages/Songs/Index.vue
  src/pages/User/index.vue
  src/util/cache.js
  yarn.lock
Labels: breaking-change, bug-fixed, feature

#282 🐛修复无法播放的问题
  src/config/blocked.json
  src/pages/Music/_id.vue
Labels: bug-fixed, critical
